[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./data" }]

[etherscan]
blast = { key = "${BLASTSCAN_KEY}", url = "https://api.blastscan.io/api", chain = 81457 }
